Repository UMC-Inha/8th_Spring_Practice_Mission, pull requests merged in 2025-05, with the labels that each got.

#4 [5주차/밥] 워크북 제출합니다.
  .github/PULL_REQUEST_TEMPLATE
  .gitignore
  README.md
  src/main/java/umc/Application.java
  src/main/java/umc/study/domain/FoodCategory.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/Mission.java
  src/main/java/umc/study/domain/Region.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/domain/ReviewImage.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/domain/Terms.java
  src/main/java/umc/study/domain/common/BaseEntity.java
  src/main/java/umc/study/domain/enums/Gender.java
  src/main/java/umc/study/domain/enums/MemberStatus.java
  src/main/java/umc/study/domain/enums/MissionStatus.java
  src/main/java/umc/study/domain/enums/SocialType.java
  src/main/java/umc/study/domain/mapping/MemberAgree.java
  src/main/java/umc/study/domain/mapping/MemberMission.java
  src/main/java/umc/study/domain/mapping/MemberPrefer.java
  src/main/resources/application.yml
Labels: Chapter05

#5 [5주차/아이번] 워크북 제출합니다
  .github/PULL_REQUEST_TEMPLATE
  .gitignore
  README.md
  src/main/java/umc/Application.java
  src/main/java/umc/Entity/BaseTimeEntity.java
  src/main/java/umc/Entity/alert/Alert.java
  src/main/java/umc/Entity/alert/AlertCategory.java
  src/main/java/umc/Entity/category/Category.java
  src/main/java/umc/Entity/category/StoreCategory.java
  src/main/java/umc/Entity/category/StoreCategoryPK.java
  src/main/java/umc/Entity/category/UserCategory.java
  src/main/java/umc/Entity/category/UserCategoryPK.java
  src/main/java/umc/Entity/inquiry/Inquiry.java
  src/main/java/umc/Entity/inquiry/InquiryAnswer.java
  src/main/java/umc/Entity/mission/Mission.java
  src/main/java/umc/Entity/mission/MissionState.java
  src/main/java/umc/Entity/mission/UserMission.java
  src/main/java/umc/Entity/mission/UserMissionPK.java
  src/main/java/umc/Entity/review/Review.java
  src/main/java/umc/Entity/review/ReviewImage.java
  src/main/java/umc/Entity/store/Store.java
  src/main/java/umc/Entity/store/StoreImage.java
  src/main/java/umc/Entity/user/Gender.java
  src/main/java/umc/Entity/user/User.java
  src/main/java/umc/Entity/user/UserState.java
  src/main/resources/application.yml
Labels: Chapter05

#11 [5주차/져니] 워크북 제출합니다.
  .github/PULL_REQUEST_TEMPLATE
  README.md
  src/main/java/umc/Application.java
  src/main/java/umc/study/domain/Alarm.java
  src/main/java/umc/study/domain/FoodCategory.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/Mission.java
  src/main/java/umc/study/domain/Region.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/domain/ReviewImage.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/domain/common/BaseEntity.java
  src/main/java/umc/study/domain/enums/Gender.java
  src/main/java/umc/study/domain/enums/MemberStatus.java
  src/main/java/umc/study/domain/enums/MissionStatus.java
  src/main/java/umc/study/domain/mapping/MemberAgree.java
  src/main/java/umc/study/domain/mapping/MemberMission.java
  src/main/java/umc/study/domain/mapping/MemberPrefer.java
  src/main/resources/application.yml
Labels: Chapter05

#14 [5주차/밤하늘] 워크북 제출합니다
  .github/PULL_REQUEST_TEMPLATE
  README.md
  build.gradle
  src/main/java/umc/domain/Comment.java
  src/main/java/umc/domain/CuisineType.java
  src/main/java/umc/domain/Location.java
  src/main/java/umc/domain/Mission.java
  src/main/java/umc/domain/PriceRange.java
  src/main/java/umc/domain/Restaurant.java
  src/main/java/umc/domain/RestaurantFood.java
  src/main/java/umc/domain/RestaurantImage.java
  src/main/java/umc/domain/Review.java
  src/main/java/umc/domain/ReviewImage.java
  src/main/java/umc/domain/User.java
  src/main/java/umc/domain/VisitPurpose.java
  src/main/java/umc/domain/common/BaseEntity.java
  src/main/java/umc/domain/enums/Gender.java
  src/main/java/umc/domain/enums/Status.java
  src/main/java/umc/domain/mapping/UserMission.java
  src/main/java/umc/domain/mapping/UserPreference.java
  src/main/resources/application.yml
Labels: Chapter05

#3 [5주차/피우] 워크북 제출합니다.
  .github/PULL_REQUEST_TEMPLATE
  README.md
  src/main/java/umc/Application.java
  src/main/java/umc/controller/UserController.java
  src/main/java/umc/controller/UserMissionController.java
  src/main/java/umc/domain/Alarm.java
  src/main/java/umc/domain/Category.java
  src/main/java/umc/domain/Inquiry.java
  src/main/java/umc/domain/Mission.java
  src/main/java/umc/domain/Region.java
  src/main/java/umc/domain/Reply.java
  src/main/java/umc/domain/Restaurant.java
  src/main/java/umc/domain/RestaurantTime.java
  src/main/java/umc/domain/Review.java
  src/main/java/umc/domain/Term.java
  src/main/java/umc/domain/User.java
  src/main/java/umc/domain/common/BaseEntity.java
  src/main/java/umc/domain/enums/AlarmType.java
  src/main/java/umc/domain/enums/Day.java
  src/main/java/umc/domain/enums/Gender.java
  src/main/java/umc/domain/enums/MissionStatus.java
  src/main/java/umc/domain/enums/SocialType.java
  src/main/java/umc/domain/enums/UserStatus.java
  src/main/java/umc/domain/mapping/PreferredCategory.java
  src/main/java/umc/domain/mapping/UserMission.java
  src/main/java/umc/domain/mapping/UserTerm.java
  src/main/java/umc/dto/ChallengeMissionDto.java
  src/main/java/umc/dto/WithdrawUserDto.java
  src/main/java/umc/repository/AlarmRepository.java
  src/main/java/umc/repository/MissionRepository.java
  src/main/java/umc/repository/PreferredCategoryRepository.java
  src/main/java/umc/repository/ReviewRepository.java
  src/main/java/umc/repository/UserMissionRepository.java
  src/main/java/umc/repository/UserRepository.java
  src/main/java/umc/repository/UserTermRepository.java
  src/main/java/umc/service/UserMissionFacadeService.java
  src/main/java/umc/service/UserMissionService.java
  src/main/java/umc/service/UserService.java
  src/main/resources/application.yml
Labels: Chapter05

#8 [5주차/메이] 워크북 제출합니다.
  .github/PULL_REQUEST_TEMPLATE
  README.md
  build.gradle
  settings.gradle
  src/main/java/umc/Application.java
  src/main/java/umc/study/StudyApplication.java
  src/main/java/umc/study/domain/Alarm.java
  src/main/java/umc/study/domain/FoodCategory.java
  src/main/java/umc/study/domain/Inquiry.java
  src/main/java/umc/study/domain/Mission.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/domain/Terms.java
  src/main/java/umc/study/domain/User.java
  src/main/java/umc/study/domain/common/BaseEntity.java
  src/main/java/umc/study/domain/enums/Gender.java
  src/main/java/umc/study/domain/enums/MissionStatus.java
  src/main/java/umc/study/domain/enums/SocialType.java
  src/main/java/umc/study/domain/enums/UserStatus.java
  src/main/java/umc/study/domain/mapping/FoodPrefer.java
  src/main/java/umc/study/domain/mapping/UserAgree.java
  src/main/java/umc/study/domain/mapping/UserAlarm.java
  src/main/java/umc/study/domain/mapping/UserMission.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: Chapter05

#6 [5주차/루크] 워크북 제출합니다.
  .github/PULL_REQUEST_TEMPLATE
  README.md
  src/main/java/umc/Application.java
  src/main/java/umc/domain/Alarm.java
  src/main/java/umc/domain/FoodCategory.java
  src/main/java/umc/domain/Inquiry.java
  src/main/java/umc/domain/InquiryImg.java
  src/main/java/umc/domain/Member.java
  src/main/java/umc/domain/Mission.java
  src/main/java/umc/domain/Review.java
  src/main/java/umc/domain/ReviewImg.java
  src/main/java/umc/domain/Store.java
  src/main/java/umc/domain/StoreImg.java
  src/main/java/umc/domain/common/BaseEntity.java
  src/main/java/umc/domain/enums/AlarmStatus.java
  src/main/java/umc/domain/enums/Gender.java
  src/main/java/umc/domain/enums/InquiryStatus.java
  src/main/java/umc/domain/enums/MemberStatus.java
  src/main/java/umc/domain/enums/MissionStatus.java
  src/main/java/umc/domain/enums/StoreStatus.java
  src/main/java/umc/domain/mapping/MemberAlarm.java
  src/main/java/umc/domain/mapping/MemberMission.java
  src/main/java/umc/domain/mapping/PreferFoodCategory.java
  src/main/resources/application.yml
Labels: Chapter05

#13 [5주차/노먼] 워크북 제출합니다.
  .github/PULL_REQUEST_TEMPLATE
  README.md
  src/main/java/umc/Application.java
  src/main/java/umc/domain/AgreeSet.java
  src/main/java/umc/domain/Alarm.java
  src/main/java/umc/domain/Answer.java
  src/main/java/umc/domain/FoodCategory.java
  src/main/java/umc/domain/Location.java
  src/main/java/umc/domain/Member.java
  src/main/java/umc/domain/Mission.java
  src/main/java/umc/domain/OpenHours.java
  src/main/java/umc/domain/Qna.java
  src/main/java/umc/domain/QnaImg.java
  src/main/java/umc/domain/Restaurant.java
  src/main/java/umc/domain/RestaurantImg.java
  src/main/java/umc/domain/Review.java
  src/main/java/umc/domain/ReviewImg.java
  src/main/java/umc/domain/common/BaseEntity.java
  src/main/java/umc/domain/enums/DayOfWeek.java
  src/main/java/umc/domain/enums/Gender.java
  src/main/java/umc/domain/enums/LoginType.java
  src/main/java/umc/domain/enums/MissionStatus.java
  src/main/java/umc/domain/mapping/MemberMission.java
  src/main/java/umc/domain/mapping/PreferCategory.java
  src/main/java/umc/repository/AgreeSetRepository.java
  src/main/java/umc/repository/AlarmRepository.java
  src/main/java/umc/repository/AnswerRepository.java
  src/main/java/umc/repository/MemberMissionRepository.java
  src/main/java/umc/repository/MemberRepository.java
  src/main/java/umc/repository/PreferCategoryRepository.java
  src/main/java/umc/repository/QnaImgRepository.java
  src/main/java/umc/repository/QnaRepository.java
  src/main/java/umc/repository/ReviewImgRepository.java
  src/main/java/umc/repository/ReviewRepository.java
  src/main/java/umc/service/AgreeSetService.java
  src/main/java/umc/service/AlarmService.java
  src/main/java/umc/service/AnswerService.java
  src/main/java/umc/service/MemberMissionService.java
  src/main/java/umc/service/MemberService.java
  src/main/java/umc/service/PreferCategoryService.java
  src/main/java/umc/service/QnaService.java
  src/main/java/umc/service/ReviewService.java
  src/main/resources/application.yml
Labels: Chapter05

#19 [6주차/서머] 워크북 제출합니다.
  .github/PULL_REQUEST_TEMPLATE
  README.md
  build.gradle
  src/main/generated/umc/study/domain/common/QBaseEntity.java
  src/main/generated/umc/study/domain/inquiry/QInquiry.java
  src/main/generated/umc/study/domain/mapping/QPreferFood.java
  src/main/generated/umc/study/domain/mapping/QUserMission.java
  src/main/generated/umc/study/domain/mapping/QUserNotification.java
  src/main/generated/umc/study/domain/mission/QMission.java
  src/main/generated/umc/study/domain/notification/QNotification.java
  src/main/generated/umc/study/domain/review/QReview.java
  src/main/generated/umc/study/domain/store/QFoodCategory.java
  src/main/generated/umc/study/domain/store/QRegion.java
  src/main/generated/umc/study/domain/store/QStore.java
  src/main/generated/umc/study/domain/user/QUser.java
  src/main/java/umc/study/config/QueryDSLConfig.java
  src/main/java/umc/study/domain/common/BaseEntity.java
  src/main/java/umc/study/domain/enums/Gender.java
  src/main/java/umc/study/domain/enums/InquiryStatus.java
  src/main/java/umc/study/domain/enums/InquiryType.java
  src/main/java/umc/study/domain/enums/MissionStatus.java
  src/main/java/umc/study/domain/enums/NotificationType.java
  src/main/java/umc/study/domain/enums/TransactionType.java
  src/main/java/umc/study/domain/enums/UserStatus.java
  src/main/java/umc/study/domain/inquiry/Inquiry.java
  src/main/java/umc/study/domain/mapping/PreferFood.java
  src/main/java/umc/study/domain/mapping/UserMission.java
  src/main/java/umc/study/domain/mapping/UserNotification.java
  src/main/java/umc/study/domain/mission/Mission.java
  src/main/java/umc/study/domain/notification/Notification.java
  src/main/java/umc/study/domain/review/Review.java
  src/main/java/umc/study/domain/store/FoodCategory.java
  src/main/java/umc/study/domain/store/Region.java
  src/main/java/umc/study/domain/store/Store.java
  src/main/java/umc/study/domain/user/User.java
  src/main/java/umc/study/repository/StoreRepository.java
  src/main/java/umc/study/repository/StoreRepositoryCustom.java
  src/main/java/umc/study/repository/StoreRepositoryImpl.java
  src/main/java/umc/study/service/store/StoreQueryService.java
  src/main/java/umc/study/service/store/StoreQueryServiceImpl.java
Labels: Chapter06

#21 [6주차/져니] 워크북 제출합니다.
  build.gradle
  gradlew
  src/main/java/umc/Application.java
  src/main/java/umc/study/config/QueryDSLConfig.java
  src/main/java/umc/study/domain/Alarm.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/Mission.java
  src/main/java/umc/study/domain/Region.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/study/service/StoreService/StoreQueryService.java
  src/main/java/umc/study/service/StoreService/StoreQueryServiceImpl.java
Labels: Chapter06

#18 [6주차/노먼] 워크북 제출합니다.
  build.gradle
  src/main/generated/umc/domain/QAgreeSet.java
  src/main/generated/umc/domain/QAlarm.java
  src/main/generated/umc/domain/QAnswer.java
  src/main/generated/umc/domain/QFoodCategory.java
  src/main/generated/umc/domain/QLocation.java
  src/main/generated/umc/domain/QMember.java
  src/main/generated/umc/domain/QMission.java
  src/main/generated/umc/domain/QOpenHours.java
  src/main/generated/umc/domain/QQna.java
  src/main/generated/umc/domain/QQnaImg.java
  src/main/generated/umc/domain/QRestaurant.java
  src/main/generated/umc/domain/QRestaurantImg.java
  src/main/generated/umc/domain/QReview.java
  src/main/generated/umc/domain/QReviewImg.java
  src/main/generated/umc/domain/common/QBaseEntity.java
  src/main/generated/umc/domain/mapping/QMemberMission.java
  src/main/generated/umc/domain/mapping/QPreferCategory.java
  src/main/java/umc/Application.java
  src/main/java/umc/config/QueryDSLConfig.java
  src/main/java/umc/domain/Restaurant.java
  src/main/java/umc/repository/RestaurantRepository/RestaurantRepository.java
  src/main/java/umc/repository/RestaurantRepository/RestaurantRepositoryCustom.java
  src/main/java/umc/repository/RestaurantRepository/RestaurantRepositoryImpl.java
  src/main/java/umc/service/RestaurantService/RestaurantQueryService.java
  src/main/java/umc/service/RestaurantService/RestaurantQueryServiceImpl.java
  src/main/resources/application.yml
Labels: Chapter06

#16 [6주차/지니] 워크북 제출합니다.
  build.gradle
  src/main/java/umc/Application.java
  src/main/java/umc/study/config/QueryDSLConfig.java
  src/main/java/umc/study/domain/Answer.java
  src/main/java/umc/study/domain/FoodType.java
  src/main/java/umc/study/domain/Inquiry.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/Mission.java
  src/main/java/umc/study/domain/Region.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/domain/ReviewPicture.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/domain/Terms.java
  src/main/java/umc/study/domain/enums/Gender.java
  src/main/java/umc/study/domain/mapping/MemberMission.java
  src/main/java/umc/study/domain/mapping/MemberPrefer.java
  src/main/java/umc/study/domain/mapping/MemberTerms.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/study/service/StoreService/StoreQueryService.java
  src/main/java/umc/study/service/StoreService/StoreQueryServiceImpl.java
Labels: Chapter06

#28 [7주차/져니] 워크북 제출합니다.
  build.gradle
  src/main/java/umc/Application.java
  src/main/java/umc/study/apiPayload/ApiResponse.java
  src/main/java/umc/study/apiPayload/code/BaseCode.java
  src/main/java/umc/study/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/study/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/study/apiPayload/code/ReasonDTO.java
  src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/study/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/study/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/study/apiPayload/exception/GeneralException.java
  src/main/java/umc/study/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/study/converter/TempConverter.java
  src/main/java/umc/study/service/TempService/TempCommandService.java
  src/main/java/umc/study/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/study/service/TempService/TempQueryService.java
  src/main/java/umc/study/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/study/web/controller/TempRestController.java
  src/main/java/umc/study/web/dto/TempRequest.java
  src/main/java/umc/study/web/dto/TempResponse.java
Labels: Chapter07

#31 [7주차/지니] 워크북 제출합니다.
  build.gradle
  src/main/java/umc/study/apiPayload/ApiResponse.java
  src/main/java/umc/study/apiPayload/code/BaseCode.java
  src/main/java/umc/study/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/study/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/study/apiPayload/code/ReasonDTO.java
  src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/study/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/study/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/study/apiPayload/exception/GeneralException.java
  src/main/java/umc/study/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/study/converter/TempConverter.java
  src/main/java/umc/study/service/TempService/TempCommandService.java
  src/main/java/umc/study/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/study/service/TempService/TempQueryService.java
  src/main/java/umc/study/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/study/web/controller/TempRestController.java
  src/main/java/umc/study/web/dto/TempRequest.java
  src/main/java/umc/study/web/dto/TempResponse.java
Labels: Chapter07

#35 [7주차/메이] 워크북 제출합니다.
  src/main/generated/umc/study/domain/QAlarm.java
  src/main/generated/umc/study/domain/QFoodCategory.java
  src/main/generated/umc/study/domain/QInquiry.java
  src/main/generated/umc/study/domain/QMission.java
  src/main/generated/umc/study/domain/QRegion.java
  src/main/generated/umc/study/domain/QReview.java
  src/main/generated/umc/study/domain/QStore.java
  src/main/generated/umc/study/domain/QTerms.java
  src/main/generated/umc/study/domain/QUser.java
  src/main/generated/umc/study/domain/common/QBaseEntity.java
  src/main/generated/umc/study/domain/mapping/QFoodPrefer.java
  src/main/generated/umc/study/domain/mapping/QUserAgree.java
  src/main/generated/umc/study/domain/mapping/QUserAlarm.java
  src/main/generated/umc/study/domain/mapping/QUserMission.java
  src/main/java/umc/study/StudyApplication.java
  src/main/java/umc/study/apiPayload/ApiResponse.java
  src/main/java/umc/study/apiPayload/code/BaseCode.java
  src/main/java/umc/study/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/study/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/study/apiPayload/code/ReasonDTO.java
  src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/study/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/study/apiPayload/exceptition/ExceptionAdvice.java
  src/main/java/umc/study/apiPayload/exceptition/GeneralException.java
  src/main/java/umc/study/apiPayload/exceptition/handler/TempHandler.java
  src/main/java/umc/study/converter/TempConverter.java
  src/main/java/umc/study/domain/Inquiry.java
  src/main/java/umc/study/domain/Mission.java
  src/main/java/umc/study/domain/Review.java
  src/main/java/umc/study/domain/Terms.java
  src/main/java/umc/study/domain/User.java
  src/main/java/umc/study/domain/enums/MissionStatus.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepository.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepositoryCustom.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepositorylmpl.java
  src/main/java/umc/study/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/study/repository/UserMissionRepository/UserMissionRepositoryImpl.java
  src/main/java/umc/study/service/MissionService/MissionQueryService.java
  src/main/java/umc/study/service/MissionService/MissionQueryServiceImpl.java
  src/main/java/umc/study/service/RegionService/RegionQueryServiceImpl.java
  src/main/java/umc/study/service/ReviewService/ReviewQueryService.java
  src/main/java/umc/study/service/ReviewService/ReviewQueryServiceImpl.java
  src/main/java/umc/study/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/study/service/TempService/TempCommandQueryImpl.java
  src/main/java/umc/study/service/TempService/TempCommandService.java
  src/main/java/umc/study/service/TempService/TempQueryService.java
  src/main/java/umc/study/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/study/web/controller/TempRestController.java
  src/main/java/umc/study/web/dto/MissionDto.java
  src/main/java/umc/study/web/dto/TempRequest.java
  src/main/java/umc/study/web/dto/TempResponse.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: Chapter07

#22 [6, 7주차/밥] 워크북 제출합니다.
  .gitignore
  build.gradle
  src/main/java/umc/Application.java
  src/main/java/umc/study/apiPayload/ApiResponse.java
  src/main/java/umc/study/apiPayload/DiscordWebhookPayload.java
  src/main/java/umc/study/apiPayload/code/BaseCode.java
  src/main/java/umc/study/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/study/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/study/apiPayload/code/ReasonDTO.java
  src/main/java/umc/study/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/study/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/study/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/study/apiPayload/exception/GeneralException.java
  src/main/java/umc/study/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/study/config/QueryDSLConfig.java
  src/main/java/umc/study/converter/TempConverter.java
  src/main/java/umc/study/domain/Member.java
  src/main/java/umc/study/domain/Store.java
  src/main/java/umc/study/dto/MemberMissionDto.java
  src/main/java/umc/study/dto/MemberResponseDto.java
  src/main/java/umc/study/dto/RegionMissionDto.java
  src/main/java/umc/study/repository/MemberRepository/MemberRepository.java
  src/main/java/umc/study/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/umc/study/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepository.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepositoryCustom.java
  src/main/java/umc/study/repository/MissionRepository/MissionRepositoryImpl.java
  src/main/java/umc/study/repository/ReviewRepository/ReviewRepository.java
  src/main/java/umc/study/repository/ReviewRepository/ReviewRepositoryCustom.java
  src/main/java/umc/study/repository/ReviewRepository/ReviewRepositoryImpl.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/study/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/study/service/StoreService/StoreQueryService.java
  src/main/java/umc/study/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/study/service/TempService/TempCommandService.java
  src/main/java/umc/study/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/study/service/TempService/TempQueryService.java
  src/main/java/umc/study/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/study/web/controller/TempRestController.java
  src/main/java/umc/study/web/dto/TempRequest.java
  src/main/java/umc/study/web/dto/TempResponse.java
Labels: Chapter06, Chapter07

#29 [7주차/노먼] 워크북 제출합니다.
  build.gradle
  src/main/java/umc/Application.java
  src/main/java/umc/apiPayload/ApiResponse.java
  src/main/java/umc/apiPayload/code/BaseCode.java
  src/main/java/umc/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/apiPayload/code/ReasonDTO.java
  src/main/java/umc/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/apiPayload/exception/GeneralException.java
  src/main/java/umc/config/FeignClientConfig.java
  src/main/java/umc/thirdParty/discord/DiscordApiClient.java
  src/main/java/umc/thirdParty/discord/DiscordRequestDTO.java
  src/main/java/umc/thirdParty/discord/DiscordWebhookService.java
  src/main/java/umc/web/controller/TestController.java
  src/main/resources/application.yml
Labels: Chapter07

#37 [7주차/아이번] 워크북 제출합니다.
  build.gradle
  src/main/java/umc/ApiPayload/ApiResponse.java
  src/main/java/umc/ApiPayload/code/BaseCode.java
  src/main/java/umc/ApiPayload/code/BaseErrorCode.java
  src/main/java/umc/ApiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/ApiPayload/code/ReasonDTO.java
  src/main/java/umc/ApiPayload/code/status/ErrorStatus.java
  src/main/java/umc/ApiPayload/code/status/SuccessStatus.java
  src/main/java/umc/ApiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/ApiPayload/exception/GeneralException.java
  src/main/java/umc/ApiPayload/exception/handler/TempHandler.java
  src/main/java/umc/mapper/TempDTOMapper.java
  src/main/java/umc/persistence/repository/mission/MissionRepository.java
  src/main/java/umc/persistence/repository/mission/MissionRepositoryImpl.java
  src/main/java/umc/persistence/repository/store/StoreRepositoryImpl.java
  src/main/java/umc/persistence/repository/user/UserRepository.java
  src/main/java/umc/persistence/repository/user/UserRepositoryImpl.java
  src/main/java/umc/presentation/ApiResponse.java
  src/main/java/umc/presentation/controller/TempRestController.java
  src/main/java/umc/presentation/dto/ResponseEntityUtil.java
  src/main/java/umc/presentation/dto/mission/MissionCardDto.java
  src/main/java/umc/presentation/dto/mission/MissionResponse.java
  src/main/java/umc/presentation/dto/temp/TempResponse.java
  src/main/java/umc/presentation/dto/user/UserProfileDto.java
  src/main/java/umc/presentation/dto/user/UserResponse.java
  src/main/java/umc/service/store/StoreQueryService.java
  src/main/java/umc/service/store/StoreQueryServiceImpl.java
  src/main/java/umc/service/temp/TempCommandService.java
  src/main/java/umc/service/temp/TempCommandServiceImpl.java
  src/main/java/umc/service/temp/TempQueryService.java
  src/main/java/umc/service/temp/TempQueryServiceImpl.java
Labels: Chapter07

#30 [6, 7주차/레온] 워크북 제출합니다.
  .gitignore
  build.gradle
  src/main/java/umc/UMC8th/Umc8thApplication.java
  src/main/java/umc/UMC8th/apiPayload/ApiResponse.java
  src/main/java/umc/UMC8th/apiPayload/code/BaseCode.java
  src/main/java/umc/UMC8th/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/UMC8th/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/UMC8th/apiPayload/code/ReasonDTO.java
  src/main/java/umc/UMC8th/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/UMC8th/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/UMC8th/config/QueryDSLConfig.java
  src/main/java/umc/UMC8th/controller/TempRestController.java
  src/main/java/umc/UMC8th/converter/TempConverter.java
  src/main/java/umc/UMC8th/domain/InquiryNotification.java
  src/main/java/umc/UMC8th/domain/Member.java
  src/main/java/umc/UMC8th/domain/Mission.java
  src/main/java/umc/UMC8th/domain/Notification.java
  src/main/java/umc/UMC8th/domain/Store.java
  src/main/java/umc/UMC8th/dto/CreateReviewRequest.java
  src/main/java/umc/UMC8th/dto/HomeMissionResponse.java
  src/main/java/umc/UMC8th/dto/InquiryResponse.java
  src/main/java/umc/UMC8th/dto/MemberMissionResponse.java
  src/main/java/umc/UMC8th/dto/MyPageUserInfoResponse.java
  src/main/java/umc/UMC8th/dto/NotificationResponse.java
  src/main/java/umc/UMC8th/dto/TempRequest.java
  src/main/java/umc/UMC8th/dto/TempResponse.java
  src/main/java/umc/UMC8th/exception/ExceptionAdvice.java
  src/main/java/umc/UMC8th/exception/GeneralException.java
  src/main/java/umc/UMC8th/handler/TempHandler.java
  src/main/java/umc/UMC8th/repository/MemberMissionRepository/MemberMissionRepository.java
  src/main/java/umc/UMC8th/repository/MemberMissionRepository/MemberMissionRepositoryCustom.java
  src/main/java/umc/UMC8th/repository/MemberMissionRepository/MemberMissionRepositoryImpl.java
  src/main/java/umc/UMC8th/repository/MemberRepository.java
  src/main/java/umc/UMC8th/repository/MissionRepository/MissionRepository.java
  src/main/java/umc/UMC8th/repository/MissionRepository/MissionRepositoryCustom.java
  src/main/java/umc/UMC8th/repository/MissionRepository/MissionRepositoryImpl.java
  src/main/java/umc/UMC8th/repository/MyPageRepository/MyPageRepository.java
  src/main/java/umc/UMC8th/repository/MyPageRepository/MyPageRepositoryCustom.java
  src/main/java/umc/UMC8th/repository/MyPageRepository/MyPageRepositoryImpl.java
  src/main/java/umc/UMC8th/repository/ReviewRepository.java
  src/main/java/umc/UMC8th/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/UMC8th/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/UMC8th/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/UMC8th/service/ReviewService.java
  src/main/java/umc/UMC8th/service/StoreQueryService.java
  src/main/java/umc/UMC8th/service/StoreQueryServiceImpl.java
  src/main/java/umc/UMC8th/service/TempService/TempCommandService.java
  src/main/java/umc/UMC8th/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/UMC8th/service/TempService/TempQueryService.java
  src/main/java/umc/UMC8th/service/TempService/TempQueryServiceImpl.java
  src/main/resources/application.yml
Labels: Chapter06, Chapter07

#39 [8주차/노먼] 워크북 제출합니다.
  build.gradle
  src/main/java/umc/Application.java
  src/main/java/umc/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/apiPayload/exception/handler/FoodCategoryHandler.java
  src/main/java/umc/apiPayload/exception/handler/LocationHandler.java
  src/main/java/umc/apiPayload/exception/handler/MemberHandler.java
  src/main/java/umc/apiPayload/exception/handler/MissionHandler.java
  src/main/java/umc/apiPayload/exception/handler/RestaurantHandler.java
  src/main/java/umc/config/FeignClientConfig.java
  src/main/java/umc/config/SwaggerConfig.java
  src/main/java/umc/converter/member/MemberConverter.java
  src/main/java/umc/converter/memberMission/MemberMissionConverter.java
  src/main/java/umc/converter/mission/MissionConverter.java
  src/main/java/umc/converter/preferCategory/PreferCategoryConverter.java
  src/main/java/umc/converter/restaurant/RestaurantConverter.java
  src/main/java/umc/converter/review/ReviewConverter.java
  src/main/java/umc/domain/Member.java
  src/main/java/umc/domain/Restaurant.java
  src/main/java/umc/dto/member/MemberRequestDTO.java
  src/main/java/umc/dto/member/MemberResponseDTO.java
  src/main/java/umc/dto/mission/MissionRequestDTO.java
  src/main/java/umc/dto/mission/MissionResponseDTO.java
  src/main/java/umc/dto/restaurant/RestaurantRequestDTO.java
  src/main/java/umc/dto/restaurant/RestaurantResponseDTO.java
  src/main/java/umc/dto/review/ReviewRequestDTO.java
  src/main/java/umc/dto/review/ReviewResponseDTO.java
  src/main/java/umc/repository/foodCategory/FoodCategoryRepository.java
  src/main/java/umc/repository/location/LocationRepository.java
  src/main/java/umc/repository/member/MemberRepository.java
  src/main/java/umc/repository/memberMission/MemberMissionRepository.java
  src/main/java/umc/repository/mission/MissionRepository.java
  src/main/java/umc/repository/review/ReviewRepository.java
  src/main/java/umc/service/MemberMissionService.java
  src/main/java/umc/service/MemberService.java
  src/main/java/umc/service/ReviewService.java
  src/main/java/umc/service/member/MemberService.java
  src/main/java/umc/service/memberMission/MemberMissionService.java
  src/main/java/umc/service/mission/MissionService.java
  src/main/java/umc/service/restaurant/RestaurantService.java
  src/main/java/umc/service/review/ReviewService.java
  src/main/java/umc/thirdParty/discord/DiscordApiClient.java
  src/main/java/umc/thirdParty/discord/DiscordWebhookService.java
  src/main/java/umc/web/controller/TestController.java
  src/main/java/umc/web/controller/member/MemberRestController.java
  src/main/java/umc/web/controller/mission/MissionRestController.java
  src/main/java/umc/web/controller/restaurant/RestaurantRestController.java
  src/main/java/umc/web/controller/review/ReviewRestController.java
  src/main/resources/application.yml
Labels: Chapter08
